const $=id=>document.getElementById(id);
const API='https://generativelanguage.googleapis.com/v1beta/models/';
const state={mode:'chat',model:localStorage.getItem('gemini_model')||'gemini-3.6-flash',modelName:localStorage.getItem('gemini_model_name')||'Gemini 3.6 Flash',history:JSON.parse(localStorage.getItem('gemini_history')||'[]'),file:null};
const names={"gemini-3.6-flash":"Gemini 3.6 Flash","gemini-3.5-flash":"Gemini 3.5 Flash","gemini-3.1-pro-preview":"Gemini 3.1 Pro","gemini-3.1-flash-image":"Nano Banana 2"};
function save(){localStorage.setItem('gemini_history',JSON.stringify(state.history));localStorage.setItem('gemini_model',state.model);localStorage.setItem('gemini_model_name',state.modelName)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function add(role,text,img){const d=document.createElement('div');d.className='message '+role;if(text)d.textContent=text;if(img){const im=document.createElement('img');im.src=img;im.alt='Gemini image';d.appendChild(im);const a=document.createElement('a');a.href=img;a.download='gemini-image.png';a.textContent='تحميل الصورة';a.style.cssText='display:inline-block;margin-top:10px;color:#9e8fff;font-size:12px';d.appendChild(a)}$('chat').appendChild(d);$('workspace').scrollTop=$('workspace').scrollHeight;return d}
function render(){ $('chat').innerHTML=''; state.history.forEach(x=>add(x.role,x.text,x.image)); if(!state.history.length)$('hero').style.display='block'; else $('hero').style.display='none';}
function setMode(mode,prompt){state.mode=mode;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('modePill').textContent={chat:'المحادثة',image:'إنشاء الصور',research:'بحث متقدم',canvas:'Canvas'}[mode]||'المحادثة';if(mode==='image'){state.model='gemini-3.1-flash-image';state.modelName='Nano Banana 2';$('modelName').textContent=state.modelName}else if(state.model==='gemini-3.1-flash-image'){state.model='gemini-3.6-flash';state.modelName=names[state.model];$('modelName').textContent=state.modelName}if(prompt){$('prompt').value=prompt;auto();$('prompt').focus()}}
function auto(){const t=$('prompt');t.style.height='auto';t.style.height=Math.min(t.scrollHeight,150)+'px'}
async function fileToPart(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({inlineData:{mimeType:file.type,data:r.result.split(',')[1]}});r.onerror=reject;r.readAsDataURL(file)})}
async function send(){const text=$('prompt').value.trim();if(!text)return;const key=localStorage.getItem('gemini_api_key')||$('apiKey').value.trim();if(!key){$('settingsDialog').showModal();toast('أدخل Gemini API Key أولًا');return}const imageMode=state.mode==='image'||state.model==='gemini-3.1-flash-image';add('user',text);state.history.push({role:'user',text});$('prompt').value='';auto();$('hero').style.display='none';const typing=add('ai','');typing.innerHTML='<div class="typing"><i></i><i></i><i></i><span> Gemini يعمل…</span></div>';$('sendBtn').disabled=true;try{let contents=[];for(const h of state.history.slice(-12)){contents.push({role:h.role==='user'?'user':'model',parts:[{text:h.text}]})}if(state.file){const part=await fileToPart(state.file);contents[contents.length-1].parts.push(part)}let url=API+encodeURIComponent(state.model)+':generateContent';let body={contents};if(imageMode)body.generationConfig={responseModalities:['TEXT','IMAGE'],responseFormat:{image:{aspectRatio:'1:1',imageSize:'1K'}}};if(state.mode==='research')body.tools=[{google_search:{}}];const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||`HTTP ${r.status}`);typing.remove();let out='',img='';const parts=data?.candidates?.[0]?.content?.parts||[];for(const p of parts){if(p.text)out+=p.text;if(p.inlineData?.data)img='data:'+(p.inlineData.mimeType||'image/png')+';base64,'+p.inlineData.data}add('ai',out||'تم إنشاء المحتوى.',img);state.history.push({role:'model',text:out||'تم إنشاء المحتوى.',image:img||undefined});save();state.file=null;$('attachmentInfo').textContent='يمكنك إرفاق صورة أو ملف نصي'}catch(e){typing.remove();add('ai','حدث خطأ: '+e.message);toast('تعذر تنفيذ الطلب — راجع المفتاح والنموذج والحصة')}finally{$('sendBtn').disabled=false;$('prompt').focus()}}
$('sendBtn').onclick=send;$('prompt').addEventListener('input',auto);$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
$('newChat').onclick=()=>{state.history=[];save();render();$('prompt').focus();if(innerWidth<850)$('sidebar').classList.remove('open')};$('clearBtn').onclick=()=>{$('newChat').click()};
$('modelButton').onclick=()=>$('modelMenu').classList.toggle('open');document.addEventListener('click',e=>{if(!e.target.closest('#modelPicker'))$('modelMenu').classList.remove('open')});document.querySelectorAll('#modelMenu button[data-model]').forEach(b=>b.onclick=()=>{state.model=b.dataset.model;state.modelName=b.dataset.name;$('modelName').textContent=state.modelName;save();$('modelMenu').classList.remove('open');toast('تم اختيار '+state.modelName)});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>setMode(b.dataset.mode||'chat',b.dataset.prompt));
$('plusBtn').onclick=()=>$('attachMenu').classList.toggle('open');$('fileBtn').onclick=()=>{$('fileInput').click();$('attachMenu').classList.remove('open')};$('imageBtn').onclick=()=>{$('fileInput').accept='image/*';$('fileInput').click();$('attachMenu').classList.remove('open')};$('cameraBtn').onclick=()=>{$('fileInput').accept='image/*';$('fileInput').capture='environment';$('fileInput').click();$('attachMenu').classList.remove('open')};$('fileInput').onchange=e=>{state.file=e.target.files[0]||null;if(state.file)$('attachmentInfo').textContent='مرفق: '+state.file.name};
function openSettings(){$('apiKey').value=localStorage.getItem('gemini_api_key')||'';$('settingsDialog').showModal()}$('settingsBtn').onclick=openSettings;$('settingsTop').onclick=openSettings;$('closeSettings').onclick=()=>$('settingsDialog').close();$('toggleKey').onclick=()=>{$('apiKey').type=$('apiKey').type==='password'?'text':'password'};$('saveSettings').onclick=()=>{const k=$('apiKey').value.trim();if(k)localStorage.setItem('gemini_api_key',k);$('settingsDialog').close();toast('تم حفظ الإعدادات على هذا الجهاز')};document.querySelectorAll('.theme').forEach(b=>b.onclick=()=>{document.body.dataset.theme=b.dataset.theme;document.querySelectorAll('.theme').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.theme==='light'){document.documentElement.style.setProperty('--bg','#eef3f9');document.documentElement.style.setProperty('--text','#111827');document.documentElement.style.setProperty('--panel','#fff')}else location.reload()});
$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');render();
